CREATE TABLE [dbo].[tblGroupInvite]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [OwnerUserId] UNIQUEIDENTIFIER NOT NULL, 
    [TargetUserId] UNIQUEIDENTIFIER NOT NULL, 
    [TargetGroupId] UNIQUEIDENTIFIER NOT NULL, 
    [InviteStatus] INT NOT NULL
)
